// Generated by ts-to-zod
import {z} from 'zod'

import {baseProfileSchema} from './baseProfile'

export const animal2PostSchema = baseProfileSchema.extend({
  animalId: z.string(),
  postId: z.string()
})
