// Generated by ts-to-zod
import {z} from 'zod'

import {baseSchemaSchema} from './baseSchema'

export const baseProfileSchema = baseSchemaSchema.extend({
  type: z.string(),
  name: z.string(),
  profileImageUrl: z.string(),
  bannerImageUrl: z.string(),
  description: z.string().optional(),
  followers: z.number().optional(),
  following: z.number().optional(),
  birthday: z.string().optional()
})
