// Generated by ts-to-zod
import {z} from 'zod'

export const baseSchemaSchema = z.object({
  id: z.string().optional(),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
  deleteAt: z.number().optional()
})

export const baseSchemaReadOnlyFieldsSchema = z.union([
  z.literal('id'),
  z.literal('createdAt'),
  z.literal('updatedAt')
])
