// Generated by ts-to-zod
import {z} from 'zod'

import {baseSchemaSchema} from './baseSchema'
import {mentionSchema} from './mention'

export const postSchema = baseSchemaSchema.extend({
  mediaType: z.union([z.literal('image'), z.literal('video'), z.literal('text')]),
  mediaUrl: z.string().optional(),
  text: z.string().optional(),
  mentions: z.array(mentionSchema).optional(),
  userId: z.string(),
  pinned: z.boolean()
})

export const postPatchSchema = postSchema.omit({id: true, createdAt: true, updatedAt: true})
